### ISSUE TITLE
Having attributes with no values

### ISSUE THREAD

**Issue by er1c** [com-lihaoyi/scalatags#33]
I was looking to do something like:

```
span("itemscope".attr, "itemtype".attr := "http://data-vocabulary.org/Breadcrumb")
```

go generate:

```
<span itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
```

Reference to usage: https://support.google.com/webmasters/answer/185417?hl=en

Is this possible somehow?

**Comment by mdedetrich** [comment]
Would making a shorthand function for this be acceptable. The reason I am asking is that I am using `scalatags` with `AngularJS`, and the usage of attributes with no values is **incredibly** common?

**Comment by lihaoyi** [comment]
> I am using scalatags with AngularJS, and the usage of attributes with no
values is incredibly common?

Maybe. I don't care. Angular is its own stupid world, I'm happy not to
write it day to day, and hope I never will in future =D

Anyway defining your own shorthand is trivial because that's what the
library is all about. Just do it, no need to ask me for permission

**Comment by lihaoyi** [comment]
Fwiw a bunch of attributes in the default set are defined as Boolean
attributes with default values of themselves if you don't provide one. This
has happened since the last email was sent to this thread, so you should go
try it out.

Extending the set of Boolean attributes is not hard, either in user code or
in library code

**Comment by mdedetrich** [comment]
> Anyway defining your own shorthand is trivial because that's what the
library is all about. Just do it, no need to ask me for permission

Of course, was just wondering if its a silly idea to put it in the official release. If it isn't, ill just make a pull request. I was thinking of something like `emptyAttr`, which is exactly the same as a normal `attr`, it just sets the value to itself
