### ISSUE TITLE
Is there any mileage in creating an HTML to ScalaTags converter?

### ISSUE THREAD

**Issue by sixman9** [com-lihaoyi/scalatags#39]
Basically, could taking pre-existing HTML ('.html') artifacts and generating valid ScalaTags classes be of any use at all? This isn't a problem per se, just an idea. 

To explain further:
1. I like the ScalaTags idea, as far as working mostly in Scala, programmatically.
2. I can't, always, design a web page mentally, as I'm not an HTML guru.
3. I might like to 'extend' a basic webpage design with programmatic functionality, such as for-loops etc., or to combine several predefined HTML 'widgets'
4. I could, possibly, design and visualise my basic HTML, easier, using a standard web-design tool.
## An SBT HTML-to-Scalatags converter?

What I'm proposing is something like **an SBT Plugin(?)**. When pointed at an HTML-containing directory (or appropriately named HTML files), **the plugin would emit valid Scalatags-based Scala classes**. The generated classes could then be imported into the codebase and edited within the project, as normal.

To do this conversion, I suggest a library such as [TreeHugger](https://github.com/eed3si9n/treehugger), for Scala class file ('.scala') generation and any of a multitude of HTML parsers available for the JVM. 
## Parse HTML to an XML DOM Tree using Neko HTML etc. 

[This](http://stackoverflow.com/questions/13642324/parsing-html-file-to-dom-tree-for-extract-java/13693605#13693605) Stackoverflow post, '[parsing html file to dom tree for extract java](http://stackoverflow.com/questions/13642324/parsing-html-file-to-dom-tree-for-extract-java/13693605#13693605)' demonstrates the use [Neko HTML](http://nekohtml.sourceforge.net) parser (Java) to correct the HTML input to well-formed HTML (XHTML). The resulting document is then parsed into **an XML DOM tree, which could then be used, along with TreeHugger, to generate valid Scalatags code**.

I'd be interested to hear any thoughts you might have on this.

Cheers

**Comment by deterdw** [comment]
If anyone is still interested in this, I have a basic translator from Html to ScalaTags source code with support for making reusable layouts: https://github.com/deterdw/scalatags-gen 

It doesn't use TreeHugger, but some basic string manipulation after the hard parsing work has been done by JSoup, gives reasonable results for me.

**Comment by scalway** [comment]
if  anyone wants to convert html to scalatags online: 
http://scalway.com/scalatags

**Comment by ikamthania** [comment]
[Here](https://github.com/simerplaha/html-to-scalatags-converter) is another one, it converts to scalajs-react scalatags too.

**Comment by scf37** [comment]
Here is another one, HTML to Scalatags only but I put some effort into quality:
source: https://github.com/scf37/html2scalatags
online: https://scf37.me/tools/html-to-scalatags-converter
